### ISSUE TITLE
Server crash when flying over a swamp - log attached

### ISSUE THREAD

**Issue by EnkiTWS** [techno-sam/ServerMobs#10]
---- Minecraft Crash Report ----
// Sorry :(

Time: 2022-11-11 20:00:13
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "com.slimeist.server_mobs.api.server_rendering.model.BakedServerEntityModel.createInstance(net.minecraft.class_1297)" because the return value of "com.slimeist.server_mobs.entities.CrocodileEntity.getBakedModel()" is null
	at com.slimeist.server_mobs.entities.CrocodileEntity.createModelInstance(CrocodileEntity.java:290)
	at com.slimeist.server_mobs.entities.CrocodileEntity.getModelInstance(CrocodileEntity.java:296)
	at com.slimeist.server_mobs.entities.CrocodileEntity.method_5773(CrocodileEntity.java:221)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zcl000$modifiedRunLoop(MinecraftServer.java:3385)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.slimeist.server_mobs.entities.CrocodileEntity.createModelInstance(CrocodileEntity.java:290)
	at com.slimeist.server_mobs.entities.CrocodileEntity.getModelInstance(CrocodileEntity.java:296)
	at com.slimeist.server_mobs.entities.CrocodileEntity.method_5773(CrocodileEntity.java:221)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: server_mobs:crocodile (com.slimeist.server_mobs.entities.CrocodileEntity)
	Entity ID: 1681
	Entity Name: Crocodile
	Entity's Exact location: 52.50, 61.00, 456.50
	Entity's Block location: World: (52,61,456), Section: (at 4,13,8 in 3,3,28; chunk contains blocks 48,-64,448 to 63,319,463), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zcl000$modifiedRunLoop(MinecraftServer.java:3385)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Enki1'/344, l='ServerLevel[Atlascraft]', x=67.98, y=101.78, z=559.83]]
	Chunk stats: 5247
	Level dimension: minecraft:overworld
	Level spawn location: World: (-47,64,214), Section: (at 1,0,6 in -3,4,13; chunk contains blocks -48,-64,208 to -33,319,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 303098086 game time, 246285110 day time
	Level name: Atlascraft
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 4857 (now: false), thunder time: 6044 (now: true)
	Known server brands: Purpur, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zcl000$modifiedRunLoop(MinecraftServer.java:3385)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.10.0-10-amd64
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3933516000 bytes (3751 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 94892.41
	Virtual memory used (MB): 74231.86
	Swap memory total (MB): 30501.00
	Swap memory used (MB): 681.75
	JVM Flags: 20 total; -Xms6G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		armorstatues: Armor Statues 4.0.2
		carpet: Carpet Mod 1.4.84
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		essential_commands: Essential Commands 0.30.0-mc1.19.2
			ec-core: Essential Commands Core 1.3.0-mc1.19.2
			org_yaml_snakeyaml: snakeyaml 1.33
			playerabilitylib: Pal 1.6.0
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		forgeconfigapiport: Forge Config API Port 4.2.6
		invview: InvView 1.4.9-1.19+
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.10.1
		luckperms: LuckPerms 5.4.46
		minecraft: Minecraft 1.19.2
		nbtcrafting: NBT Crafting 2.2.2+mc1.19
		phosphor: Phosphor 0.8.1
		polymer-all: Polymer (Packed) 0.2.18+1.19.2
			polymer: Polymer (Core) 0.2.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-autohost: Polymer Auto Host 0.1.4+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		ring_of_attraction: Ring Of Attraction 1.3.14
		sdlink: Simple Discord Link 2.0.1
			me_hypherionmc_sdlink_sdlink-lib: sdlink-lib 2.1.5
		server_mobs: Server Mobs 1.0.8+1.19.2
			hologram-api: Hologram API 0.2.2+1.19
		server_mobs_api: Server Mobs API 1.0.5+1.19.2
		servercore: ServerCore 1.3.3-1.19.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_github_llamalad7_mixinextras: MixinExtras 0.1.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
		servux: Servux 0.1.0
		simplevillagers: Simple Villagers 1.4.1
			config2brigadier: Config to Brigadier 1.2.1
		universal-graves: Universal Graves 2.1.3+1.19.2
			common-protection-api: Common Protection API 1.0.0
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
			sgui: sgui 1.1.5+1.19.1
		voicechat: Simple Voice Chat 1.19.2-2.3.13
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		xaerominimap: Xaero's Minimap 22.16.2
		xaeroworldmap: Xaero's World Map 1.28.3
	Server Running: true
	Player Count: 1 / 20; [class_3222['Enki1'/344, l='ServerLevel[Atlascraft]', x=67.98, y=101.78, z=559.83]]
	Data Packs: vanilla, file/Custom-Stonecutter.zip (incompatible), file/hammersdatapack-e3460.zip (incompatible), Fabric Mods, file/armor statues v2.8.4.zip, file/count mob deaths v1.1.3.zip, file/double shulker shells v1.3.3.zip, file/durability ping v1.1.3.zip, file/fast leaf decay v2.0.6.zip, file/more mob heads v2.10.0.zip, file/player head drops v1.1.3.zip, file/silence mobs v1.1.3.zip, file/spectator conduit power v1.1.3.zip, file/track raw statistics v1.5.3.zip, file/track statistics v1.1.4.zip, file/unlock all recipes v2.0.4.zip, file/FireFlies.zip (incompatible), file/villager workstation highlights v1.1.3.zip, file/rope.zip, file/Enkis_custom_Crafting.zip (incompatible), file/Villager_create.zip (incompatible), file/cave_cleaner.zip (incompatible), file/classic fishing loot v1.1.3.zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by techno-sam** [comment]
Try updating to latest servermobs and servermobsapi, it includes a fix for this
