### ISSUE TITLE
Converting existing mods?

### ISSUE THREAD

**Issue by fennecr** [techno-sam/ServerMobs#11]
I have been trying to convert other mods to work with servermobs with little success... is there a way to automatically render mobs like PolyMC converts items and blocks? Or is there a more beginner friendly tutorial for converting mods that could be made? 

Sorry if I am misunderstanding the aim of this project, this is the only way I've found to do serverside mobs.

**Comment by techno-sam** [comment]
There's not really a way to do that, given that the .bbmodel files this project uses are completely different from the clientside-only rendering code that would otherwise be used

**Comment by techno-sam** [comment]
You should be able to use polymc for most things, and just use polymer+ServerMobs for your mobs

**Comment by fennecr** [comment]
The mod I'm trying to convert, Deeper and Darker, uses .bbmodels natively anyways, so I am past that hurdle regardless.
What do you mean polymer+Servermobs in this case, do you mean it automatically generates them?
