### ISSUE TITLE
Mod is not working

### ISSUE THREAD

**Issue by ghost** [techno-sam/ServerMobs#9]
Hello, first I had the crash from issue #8.

It loads fine now and I was searching for a swamp again.
The server doesn't crash anymore but I can't see any crocodiles - I'm getting this server message here:

[23:00:26] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:26] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile
[23:00:27] [Server thread/ERROR]: Failed to handle entity type entity.server_mobs.crocodile

Using the latest version of ServerMobs, ServerMobs API, NBTCrafting and Polymer.

**Comment by techno-sam** [comment]
I just updated ServerMobs (and API) with the latest polymer. Could you try if it works now?
API `v1.0.5`
MOD `v1.0.6`

**Comment by ghost** [comment]
Hello @techno-sam, sorry for the late response.
I wanted to try the newest version but I ran currently into a problem on my server, which I need to fix first.
But I am curious - could it be in relation with your mods?
https://pastebin.com/raw/VUjnKnsp

Thanks already.

I have only three Datapacks and I never had such problems with them.
![image](https://user-images.githubusercontent.com/75373609/192116410-d86d37ba-86fa-43cc-adfc-111857aa87e7.png)

**Comment by ghost** [comment]
I spotted the error, It came from GeyserMC.
Using the latest versions but still can't see any crocodiles 😂
Walking around in the swamp biome and getting this log again:

![image](https://user-images.githubusercontent.com/75373609/192118118-5bf89588-66f0-45b7-91a6-1c9771af46f5.png)

**Comment by techno-sam** [comment]
Hi, I'll take a look and see if I can figure this out.

**Comment by techno-sam** [comment]
Could you give me more information on your server setup. I'm unable to recreate this, and the error you sent me isn't showing up in my code or the minecraft code, so I'm not sure where it's coming from.

Eg: Mods list, and other relevant server software

**Comment by techno-sam** [comment]
Okay, I think I found the mod causing this incompatibility: https://github.com/WearBlackAllDay/DimensionalThreading. Can you confirm that you have this mod installed?

**Comment by ghost** [comment]
Hello @techno-sam, I send you soon my mod list 😊

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/75373609/193616617-d3d2beaf-82d2-4bdf-9646-289d5d4a594e.png)
![image](https://user-images.githubusercontent.com/75373609/193616638-c1fecfb6-7e00-4372-93c6-9b8c4e3841a6.png)
![image](https://user-images.githubusercontent.com/75373609/193616655-195a5fba-e23a-4917-b268-f97912581532.png)
![image](https://user-images.githubusercontent.com/75373609/193616674-e0187854-1640-485f-8536-cdfd38d9d212.png)
![image](https://user-images.githubusercontent.com/75373609/193616692-9c6ee5e0-3c70-4882-8b25-f148f435b278.png)
![image](https://user-images.githubusercontent.com/75373609/193616710-bf46b614-acd5-419e-8b1f-0d6687c2365e.png)
![image](https://user-images.githubusercontent.com/75373609/193616734-2622e1c3-7f1f-4b92-bc20-632dadcca492.png)

**Comment by techno-sam** [comment]
Okay... That's a lot. Could you make a backup of your world and remove mods until mine works, so that we know which mod is causing the incompatibility? Thanks!

**Comment by ghost** [comment]
Hello @techno-sam, I was trying to check how this works on a clean test server. But I am not able to see the custom textures.
I was thinking if this could come from my modpack, but even as vanilla I'm not able to see it.

![2022-10-06_23 22 23](https://user-images.githubusercontent.com/75373609/194421380-796f18d6-0ba3-4f83-a7f1-0b6160183133.png)

![image](https://user-images.githubusercontent.com/75373609/194421444-64cf9f14-d1f9-49f4-96ec-22ccc69eb89c.png)

Is this log error fine?

![image](https://user-images.githubusercontent.com/75373609/194422231-ad169d87-7414-4333-b6e5-f9b45c0a97fe.png)

**Comment by techno-sam** [comment]
hm... that error there is an error with the server_translations_api mod, i am not sure where the github for it is.
For the representation of crocodiles - check that you have server resource packs enabled.
![Screenshot from 2022-10-06 20-37-07](https://user-images.githubusercontent.com/77073745/194462760-9bd28933-cb04-40f0-a076-61d42ac742eb.png)

**Comment by techno-sam** [comment]
Otherwise, could you send me the ip of your **clean** test server, so I can hop on and check for myself?
MC username `Slimeist` for whitelist

**Comment by ghost** [comment]
Yep, the texture pack was the problem. But I got no notification to receive it, mhh.
I was installing it now manually - and voilà it works:)

WTHIT shows the names a bit different, maybe it helps.
Gust (Slime) - which is good.
Turtle - for the crocodile, mhh.

**Comment by techno-sam** [comment]
Make sure you set up polymer autohost properly. You need to enable it, and make sure it has a public ip and port your client can connect to.

For the WTHIT thing, I will fix that soon.

**Comment by ghost** [comment]
I wasn't making this, thanks for letting me know.

I will test soon some mods and see which is causing the creation error.


Could you add maybe the config options to decide what things you really want to enable and integrate?
Since it adds two mobs, one attack I think, custom item/armor? Achievement. I would like to have full control over this.

It is impressive work you have made done here ❤️

It will be interesting to see, how much compatible this is with GeyserMC. You can define over GeyserMC server resource packs. Or I just send the player the resource pack for direct install. I was reading this works great and you just need to convert your resource pack. (Wasn't testing this yet.) 

But not sure how good this works with GeyserMC 😅
This mod is a candidate for me, who is causing maybe the bug. I will write again when I have some testing done 😇

**Comment by techno-sam** [comment]
I highly doubt it will work with Geyser, since Bedrock has a completely different mod/rp system, that is unlikely to work with ServerMobs. Totally will add config options. Good luck, in any case.

**Comment by techno-sam** [comment]
Config update released! ServerMobs 1.0.8+1.19.2

**Comment by techno-sam** [comment]
Is this resolved then?

**Comment by ghost** [comment]
Hello, please keep this open until I figured out which mod is blocking the creation.

**Comment by techno-sam** [comment]
Okay
